export const DISPLAY_ORDER = {
	BURST_WINDOW: 1,
	SONGS_WINDOWS: 2,
	ARMYS_MUSE: 3,
	RAGING_STRIKES: 4,
	BATTLE_VOICE: 5,
	RADIANT_FINALE: 6,
	DRIFTING_EA: 7,
	REFULGENT_PROCS: 8,
	MULTI_HIT_SKILLS: 9,
}
