// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace SongsWindowsModuleCssNamespace {
  export interface ISongsWindowsModuleCss {
    checkbox: string;
    gapSegment: string;
    gutter: string;
    legend: string;
    legendColor: string;
    legendItem: string;
    songBar: string;
    songSegment: string;
  }
}

declare const SongsWindowsModuleCssModule: SongsWindowsModuleCssNamespace.ISongsWindowsModuleCss;

export = SongsWindowsModuleCssModule;
